# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'FontAwesomeKit', '~> 2.2'
pod 'Masonry'

target 'Face Paint' do

end

target 'Face PaintTests' do

end

target 'Face PaintUITests' do

end

